# Generated by Django 2.1.7 on 2019-03-24 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Esper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.BooleanField(default=False)),
                ('inited', models.BooleanField(default=False)),
                ('place', models.CharField(default='', max_length=20)),
                ('keep', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(default='', max_length=20)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Switchee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('place', models.CharField(default='', max_length=20)),
                ('state', models.IntegerField(default=0)),
                ('reverse', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Switcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('place', models.CharField(default='', max_length=20)),
                ('lastV', models.DateTimeField(verbose_name='lastVerified')),
                ('lastVP', models.CharField(max_length=20)),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('switchee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='homes.Switchee')),
                ('typ', models.CharField(default='I', max_length=5)),
            ],
            bases=('homes.switchee', models.Model),
        ),
        migrations.CreateModel(
            name='PWM',
            fields=[
                ('switchee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='homes.Switchee')),
                ('typ', models.CharField(default='P', max_length=5)),
                ('max', models.PositiveSmallIntegerField(default=1024)),
                ('min', models.SmallIntegerField(default=0)),
            ],
            bases=('homes.switchee', models.Model),
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('switchee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='homes.Switchee')),
                ('typ', models.CharField(default='S', max_length=5)),
            ],
            bases=('homes.switchee', models.Model),
        ),
        migrations.AddField(
            model_name='switchee',
            name='switcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homes.Switcher'),
        ),
        migrations.AddField(
            model_name='esper',
            name='switcher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homes.Switcher'),
        ),
    ]
